[package]
name = "qr_nif"
version = "0.1.0"
authors = []

[lib]
name = "qr_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.18.0"
rustler_codegen = "0.18.0"
lazy_static = "1.0"
image = "0.19.0"
qrcode = "0.8.0"
bytes = "0.4.10"
